export const Messages = {
  TITLE: "Must be 15 characters or less",
  DESCRIPTION: "Must be at least 5 characters or less",
  USERNAME: "Must be 15 characters or less",
  INVALID_EMAIL: "Invalid email format",
  NO_PASSWORD: "No password provided.",
  SHORT_PASWORD: "Password must be at least 8 characters",
  REQUIRED: "Required",
  NO_FILE: "No file uploaded",
  LARGE_FILE_LIST: "One or more files are too large",
  LARGE_FILE: "File is too large",
  NOT_IMPLEMENTED: "Not implemented",
  ERROR_LOAD: "Sorry we couldn't load the data",
  FILE_NAME_DUPLICATE: "file name already exists",
  TITLE_DUPLICATE: "title already exists",
  PASSWORD_MISMATCH: "Passwords must match",
  EMPTY_PLAYLISTS: "You have no playlists",
  EMPTY_RELEASES: "You have no releases",
  EMPTY_TRACKS: "You have no tracks",
  DISCONNECTED: "Disconnected",
  UNAUTHORIZED: "Unauthorized please login",
  DONATION_ERROR: "Sorry the donation couldn't be done",
  PURCHASE_ERROR: "Sorry the purchase couldn't be done",
  DONATION_SUCCESS: "Thank you for your support",
  PURCHASE_SUCCESS: "Thank you for your purchase",
  EMPTY_FUZZY_RESULT: "No results with those specifications",
};
